name: Release Pipeline

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Package
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish Windows x64
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true -o ./publish/win-x64
        
      - name: Create ZIP archive for Windows
        run: |
          Compress-Archive -Path ./publish/win-x64/* -DestinationPath ./UAssetGUI_Windows_x64_cn.zip
          
      # 根据需要添加其他平台的构建步骤
      
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./UAssetGUI_Windows_x64_cn.zip
            # 可以添加其他平台的压缩包
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
